"""Range channel: protocol v3, codec, channel client, and conformance mocks.

The wire contract is specified in `design/inspect-ranges/range-channel.md` and the phase plan in `design/inspect-ranges/channel-v1.md`. Everything arriving over the channel is untrusted input: replies are strict-schema validated and byte caps are enforced reader-side.
"""

from .channel import (
    ChannelBudgetError,
    ChannelError,
    ExecOutcome,
    FileLimitExceeded,
    GuestError,
    HostRefused,
    IllegalTransition,
    LoopbackTransport,
    MessageChannel,
    RangeChannel,
    SamplePhase,
    SampleStateMachine,
    TamperError,
    Transport,
    TransportFailure,
    request_id,
    run_sample,
)
from .codec import (
    BulkMismatch,
    BulkOverrun,
    ChannelClosed,
    DecodeError,
    EncodeError,
    FrameTooLarge,
    FrameType,
    InvalidMessage,
    MessageStreamReader,
    ProtocolViolation,
    TraceEvent,
    TruncatedFrame,
    decode_frames,
    encode_message,
)
from .mocks import (
    HOSTILE_APPLIER_SCENARIOS,
    HOSTILE_GUEST_SCENARIOS,
    DribbleTransport,
    HostileApplierTransport,
    HostileTransport,
    LatencyTransport,
)
from .protocol import PROTOCOL_VERSION, Budget, Heartbeat, Message
from .vsock import VsockTransport

__all__ = [
    "Budget",
    "BulkMismatch",
    "BulkOverrun",
    "ChannelBudgetError",
    "ChannelClosed",
    "ChannelError",
    "DecodeError",
    "EncodeError",
    "ExecOutcome",
    "FileLimitExceeded",
    "FrameTooLarge",
    "FrameType",
    "GuestError",
    "HOSTILE_APPLIER_SCENARIOS",
    "Heartbeat",
    "HostRefused",
    "HOSTILE_GUEST_SCENARIOS",
    "DribbleTransport",
    "HostileApplierTransport",
    "HostileTransport",
    "IllegalTransition",
    "InvalidMessage",
    "LatencyTransport",
    "LoopbackTransport",
    "Message",
    "MessageChannel",
    "MessageStreamReader",
    "PROTOCOL_VERSION",
    "ProtocolViolation",
    "RangeChannel",
    "SamplePhase",
    "SampleStateMachine",
    "TamperError",
    "TraceEvent",
    "Transport",
    "TransportFailure",
    "TruncatedFrame",
    "VsockTransport",
    "decode_frames",
    "encode_message",
    "request_id",
    "run_sample",
]
