import json
from dataclasses import asdict
from itertools import groupby

import click

from ._result import CheckResult, CheckStatus

_SYMBOLS: dict[CheckStatus, tuple[str, str]] = {
    "ok": ("✓", "green"),
    "warn": ("!", "yellow"),
    "fail": ("✗", "red"),
    "skip": ("-", "bright_black"),
}


def passed(results: list[CheckResult]) -> bool:
    """Whether no check failed (warnings and skips don't count)."""
    return not any(result.status == "fail" for result in results)


def render_text(results: list[CheckResult]) -> str:
    """Render results grouped under headings, with a fix line for each warning or failure."""
    width = max((len(result.name) for result in results), default=0)
    lines: list[str] = []
    for group, group_results in groupby(results, key=lambda result: result.group):
        lines.append(click.style(group, bold=True))
        for result in group_results:
            symbol, color = _SYMBOLS[result.status]
            lines.append(
                f"  {click.style(symbol, fg=color)} {result.name.ljust(width)}  {result.detail}"
            )
            if result.fix and result.status in ("warn", "fail"):
                lines.append(f"  {' ' * (width + 4)}fix: {result.fix}")
    counts = {
        status: sum(result.status == status for result in results)
        for status in _SYMBOLS
    }
    lines.append("")
    lines.append(
        f"{counts['ok']} ok, {counts['warn']} warning(s), {counts['fail']} failed, {counts['skip']} skipped"
    )
    if any(result.fix_command for result in _problems(results)):
        lines.append(
            "run `inspect-ranges doctor --fix-script | sudo sh` to apply the runnable fixes"
        )
    return "\n".join(lines)


def render_fix_script(results: list[CheckResult]) -> str:
    """Render a shell script applying the runnable fixes for current warnings and failures.

    The script expects to run as root (`doctor --fix-script | sudo sh`); fixes that need human judgment are listed as comments at the end.
    """
    runnable = [result for result in _problems(results) if result.fix_command]
    manual = [result for result in _problems(results) if not result.fix_command]
    lines = [
        "#!/bin/sh",
        "# Generated by `inspect-ranges doctor --fix-script` from this host's failed checks.",
        "# Review, then run: inspect-ranges doctor --fix-script | sudo sh",
        "set -eu",
    ]
    if not runnable:
        lines.append("echo 'doctor: no runnable fixes needed'")
    else:
        lines.append(
            '[ "$(id -u)" -eq 0 ] || { echo "run this script with sudo" >&2; exit 1; }'
        )
        if any("$SUDO_USER" in (result.fix_command or "") for result in runnable):
            lines.append(
                ': "${SUDO_USER:?run via sudo from your user account, not a root login}"'
            )
        if any("apt-get install" in (result.fix_command or "") for result in runnable):
            lines.append("export DEBIAN_FRONTEND=noninteractive")
            lines.append("apt-get update")
        for result in runnable:
            lines.append("")
            lines.append(f"# {result.group} / {result.name}: {result.detail}")
            lines.append(result.fix_command or "")
    if manual:
        lines.append("")
        lines.append("# Not scriptable; handle manually:")
        for result in manual:
            lines.append(
                f"#   {result.group} / {result.name}: {result.fix or result.detail}"
            )
    return "\n".join(lines) + "\n"


def _problems(results: list[CheckResult]) -> list[CheckResult]:
    return [result for result in results if result.status in ("warn", "fail")]


def render_json(results: list[CheckResult]) -> str:
    """Render results as JSON: `{"passed": bool, "checks": [...]}`."""
    return json.dumps(
        {"passed": passed(results), "checks": [asdict(result) for result in results]},
        indent=2,
    )
