#!/usr/bin/env python3
"""Emit explicit libvirt domain XML for the net-compile range: every functional device is declared, no virt-install defaults decide the attack surface.

Two profiles (agent-containment backlog item 3):
- strict (agent, db, router): virtio disk x2 (root overlay + cloud-init seed as a virtio disk, not a SATA cdrom), virtio NIC(s), vsock, serial console, virtio-rng; memballoon explicitly none, USB controller explicitly none, no video/tablet/cdrom.
- target-standard (web): strict plus a video device and local VNC, demonstrating per-role emission where a scenario needs screenshots.

Reads ../net-compile/tmp/render/allocation.json; writes tmp/xml/<vm>.xml and tmp/xml/boot.sh (container-side boot script). PCI controllers and machine-inherent devices (pcie-root and its ports, i8042/PS/2) are left to libvirt: they are structural plumbing, not optional surface.
"""

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
RENDER = HERE.parent / "net-compile" / "tmp" / "render"
OUT = HERE / "tmp" / "xml"

VIDEO_VMS = {"web"}  # target profile demo: scenario-needs-screenshots role

DOMAIN = """<domain type='kvm'>
  <name>{name}</name>
  <memory unit='MiB'>1024</memory>
  <vcpu>1</vcpu>
  <os>
    <type arch='x86_64' machine='q35'>hvm</type>
    <boot dev='hd'/>
  </os>
  <features><acpi/><apic/></features>
  <cpu mode='host-passthrough'/>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>destroy</on_crash>
  <devices>
    <emulator>/usr/bin/qemu-system-x86_64</emulator>
    <disk type='file' device='disk'>
      <driver name='qemu' type='qcow2'/>
      <source file='/scratch/{name}.qcow2'/>
      <target dev='vda' bus='virtio'/>
    </disk>
    <disk type='file' device='disk'>
      <driver name='qemu' type='raw'/>
      <source file='/scratch/{name}-seed.iso'/>
      <target dev='vdb' bus='virtio'/>
      <readonly/>
    </disk>
{interfaces}    <vsock model='virtio'>
      <cid auto='no' address='{cid}'/>
    </vsock>
    <serial type='pty'><target port='0'/></serial>
    <console type='pty'><target type='serial' port='0'/></console>
    <rng model='virtio'>
      <backend model='random'>/dev/urandom</backend>
    </rng>
    <memballoon model='none'/>
    <controller type='usb' model='none'/>
{extra}  </devices>
</domain>
"""

INTERFACE = """    <interface type='bridge'>
      <source bridge='br-{network}'/>
      <mac address='{mac}'/>
      <model type='virtio'/>
    </interface>
"""

VIDEO = """    <video><model type='virtio'/></video>
    <graphics type='vnc' listen='127.0.0.1'/>
"""


def main() -> None:
    vms = json.loads((RENDER / "allocation.json").read_text())
    OUT.mkdir(parents=True, exist_ok=True)

    boot = ["#!/bin/bash", "# generated by gen-xml.py: explicit-XML boot for the net-compile range", "set -euxo pipefail"]
    for vm in vms:
        interfaces = "".join(
            INTERFACE.format(network=i["network"], mac=i["mac"]) for i in vm["interfaces"]
        )
        extra = VIDEO if vm["name"] in VIDEO_VMS else ""
        xml = DOMAIN.format(name=vm["name"], cid=vm["cid"], interfaces=interfaces, extra=extra)
        (OUT / (vm["name"] + ".xml")).write_text(xml)
        boot += [
            f"qemu-img create -f qcow2 -F qcow2 -b /images/noble-range-guest.qcow2 /scratch/{vm['name']}.qcow2 10G",
            f"cloud-localds -N /render/vms/{vm['name']}/network-config /scratch/{vm['name']}-seed.iso "
            f"/render/vms/{vm['name']}/user-data /render/vms/{vm['name']}/meta-data",
            f"virsh -c qemu:///system define /mdxml/{vm['name']}.xml",
            f"virsh -c qemu:///system start {vm['name']}",
        ]
    boot.append("virsh -c qemu:///system list")
    (OUT / "boot.sh").write_text("\n".join(boot) + "\n")
    print(f"wrote {len(vms)} domain XMLs + boot.sh to {OUT}")


if __name__ == "__main__":
    sys.exit(main())
