#!/usr/bin/env python3
"""ACL v2 conformance compiler: spec.yaml -> tmp/render, production stages where they exist.

Everything slice 2 owns comes from the production compiler (`inspect_ranges._compiler`): deterministic allocation and the router's nftables ruleset. Seeds, bridges, and the boot plan remain spike-grade glue carried over from the net-compile spike.
"""

import sys
from pathlib import Path
from typing import Any

import yaml

from inspect_ranges._compiler import allocate, render_router_nftables
from inspect_ranges.schema import load_range

HERE = Path(__file__).parent
RENDER = HERE / "tmp" / "render"
GOLDEN = "/images/noble-range-guest.qcow2"


def bridge(network: str) -> str:
    return f"br-{network}"[:15]


def main() -> None:
    spec = load_range(HERE / "spec.yaml")
    allocation = allocate(spec)
    networks = {network.name: network for network in spec.networks}

    gateways: dict[str, Any] = {}
    for guest in allocation.guests:
        if guest.kind == "router":
            for interface in guest.interfaces:
                gateways.setdefault(interface.network, interface.ip)

    for guest in allocation.guests:
        vm_dir = RENDER / "vms" / guest.name
        vm_dir.mkdir(parents=True, exist_ok=True)
        (vm_dir / "meta-data").write_text(
            f"instance-id: {spec.meta.name}-{guest.name}\nlocal-hostname: {guest.name}\n"
        )
        ethernets: dict[str, Any] = {}
        for index, interface in enumerate(guest.interfaces):
            nic = f"eth{index}"  # must match router_nic_names() for the rendered ruleset
            prefix = networks[interface.network].cidr.prefixlen
            entry: dict[str, Any] = {
                "match": {"macaddress": interface.mac},
                "set-name": nic,
                "addresses": [f"{interface.ip}/{prefix}"],
            }
            if guest.kind != "router" and interface.network in gateways:
                entry["routes"] = [
                    {"to": "default", "via": str(gateways[interface.network])}
                ]
            ethernets[nic] = entry
        (vm_dir / "network-config").write_text(
            yaml.safe_dump({"version": 2, "ethernets": ethernets}, sort_keys=False)
        )
        user_data: dict[str, Any] = {"hostname": guest.name}
        if guest.kind == "router":
            ruleset = "flush ruleset\n" + render_router_nftables(
                spec, guest.name, allocation
            )
            user_data["write_files"] = [
                {"path": "/etc/nftables.conf", "content": ruleset}
            ]
            user_data["runcmd"] = [
                ["sysctl", "-w", "net.ipv4.ip_forward=1"],
                ["systemctl", "enable", "--now", "nftables"],
            ]
        (vm_dir / "user-data").write_text(
            "#cloud-config\n" + yaml.safe_dump(user_data, sort_keys=False)
        )

    RENDER.joinpath("bridges.txt").write_text(
        "".join(f"{bridge(name)}\n" for name in networks)
    )
    RENDER.joinpath("range-netns.nft").write_text(
        "flush ruleset\n"
        "table inet rangehost {\n"
        "  chain forward { type filter hook forward priority 0; policy drop; }\n"
        "}\n"
    )
    RENDER.joinpath("allocation.json").write_text(
        allocation.model_dump_json(indent=2) + "\n"
    )

    boot = ["#!/bin/bash", "# Generated by compile.py", "set -euxo pipefail"]
    for guest in allocation.guests:
        nics = " ".join(
            f"--network bridge={bridge(interface.network)},model=virtio,mac={interface.mac}"
            for interface in guest.interfaces
        )
        boot += [
            f"qemu-img create -f qcow2 -F qcow2 -b {GOLDEN} /scratch/{guest.name}.qcow2 10G",
            f"cloud-localds -N /render/vms/{guest.name}/network-config /scratch/{guest.name}-seed.iso "
            f"/render/vms/{guest.name}/user-data /render/vms/{guest.name}/meta-data",
            f"virt-install --connect qemu:///system --name {guest.name} "
            "--memory 1024 --vcpus 1 --cpu host-passthrough "
            f"--disk path=/scratch/{guest.name}.qcow2,format=qcow2,bus=virtio "
            f"--disk path=/scratch/{guest.name}-seed.iso,device=cdrom "
            f"{nics} --vsock cid.address={guest.cid} "
            "--osinfo ubuntu24.04 --import --graphics none --noautoconsole",
        ]
    boot.append("virsh -c qemu:///system list")
    RENDER.joinpath("boot-vms.sh").write_text("\n".join(boot) + "\n")
    print(f"rendered {len(allocation.guests)} VMs -> {RENDER}")


if __name__ == "__main__":
    sys.exit(main())
