#!/usr/bin/env python3
"""Egress conformance compiler: spec.yaml -> tmp/render, production stages where they exist.

Everything slices 2-3 own comes from the production compiler (`inspect_ranges._compiler`): deterministic allocation, gateway election (hypervisor NAT), and the range-netns egress ruleset. Seeds, bridges, and the boot plan remain spike-grade glue carried over from the net-compile spike.
"""

import sys
from pathlib import Path
from typing import Any

import yaml

from inspect_ranges._compiler import (
    allocate,
    elect_gateways,
    render_egress_nftables,
)
from inspect_ranges.schema import load_range

HERE = Path(__file__).parent
RENDER = HERE / "tmp" / "render"
GOLDEN = "/images/noble-range-guest.qcow2"


def bridge(network: str) -> str:
    return f"br-{network}"[:15]


def main() -> None:
    spec = load_range(HERE / "spec.yaml")
    allocation = allocate(spec)
    networks = {network.name: network for network in spec.networks}

    gateways = elect_gateways(spec, allocation)
    routers = {router.name: router for router in spec.routers}

    for guest in allocation.guests:
        vm_dir = RENDER / "vms" / guest.name
        vm_dir.mkdir(parents=True, exist_ok=True)
        (vm_dir / "meta-data").write_text(
            f"instance-id: {spec.meta.name}-{guest.name}\nlocal-hostname: {guest.name}\n"
        )
        ethernets: dict[str, Any] = {}
        for index, interface in enumerate(guest.interfaces):
            nic = f"eth{index}"  # must match router_nic_names() for the rendered ruleset
            prefix = networks[interface.network].cidr.prefixlen
            entry: dict[str, Any] = {
                "match": {"macaddress": interface.mac},
                "set-name": nic,
                "addresses": [f"{interface.ip}/{prefix}"],
            }
            if guest.kind != "router" and interface.network in gateways:
                entry["routes"] = [
                    {"to": "default", "via": str(gateways[interface.network])}
                ]
            if guest.kind == "router":
                static = [
                    {"to": str(route.to), "via": str(route.via)}
                    for route in routers[guest.name].routes
                    if route.via in networks[interface.network].cidr  # type: ignore[operator]
                ]
                if static:
                    entry["routes"] = static
            ethernets[nic] = entry
        (vm_dir / "network-config").write_text(
            yaml.safe_dump({"version": 2, "ethernets": ethernets}, sort_keys=False)
        )
        user_data: dict[str, Any] = {"hostname": guest.name}
        (vm_dir / "user-data").write_text(
            "#cloud-config\n" + yaml.safe_dump(user_data, sort_keys=False)
        )

    RENDER.joinpath("bridges.txt").write_text(
        "".join(f"{bridge(name)}\n" for name in networks)
    )
    RENDER.joinpath("range-netns.nft").write_text(
        render_egress_nftables(spec, allocation, uplink="eth0")
    )
    RENDER.joinpath("nat-gateways.txt").write_text(
        "".join(
            f"{bridge(name)} {ip}/{networks[name].cidr.prefixlen}\n"
            for name, ip in allocation.hypervisor_addresses.items()
        )
    )
    RENDER.joinpath("allocation.json").write_text(
        allocation.model_dump_json(indent=2) + "\n"
    )

    boot = ["#!/bin/bash", "# Generated by compile.py", "set -euxo pipefail"]
    for guest in allocation.guests:
        nics = " ".join(
            f"--network bridge={bridge(interface.network)},model=virtio,mac={interface.mac}"
            for interface in guest.interfaces
        )
        boot += [
            f"qemu-img create -f qcow2 -F qcow2 -b {GOLDEN} /scratch/{guest.name}.qcow2 10G",
            f"cloud-localds -N /render/vms/{guest.name}/network-config /scratch/{guest.name}-seed.iso "
            f"/render/vms/{guest.name}/user-data /render/vms/{guest.name}/meta-data",
            f"virt-install --connect qemu:///system --name {guest.name} "
            "--memory 1024 --vcpus 1 --cpu host-passthrough "
            f"--disk path=/scratch/{guest.name}.qcow2,format=qcow2,bus=virtio "
            f"--disk path=/scratch/{guest.name}-seed.iso,device=cdrom "
            f"{nics} --vsock cid.address={guest.cid} "
            "--osinfo ubuntu24.04 --import --graphics none --noautoconsole",
        ]
    boot.append("virsh -c qemu:///system list")
    RENDER.joinpath("boot-vms.sh").write_text("\n".join(boot) + "\n")
    print(f"rendered {len(allocation.guests)} VMs -> {RENDER}")


if __name__ == "__main__":
    sys.exit(main())
